# Generated by Django 4.2.2 on 2023-11-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
