# Generated by Django 4.2.2 on 2023-11-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
