# Generated by Django 4.2.2 on 2023-11-18 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
