# Generated by Django 4.2.2 on 2023-11-17 10:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('health', 'Health'), ('food', 'Food'), ('banking', 'Banking'), ('aviation', 'Aviation'), ('ecommerce', 'E-commerce'), ('auto', 'Vehicles & Automobiles'), ('agriculture', 'Agriculture')], max_length=30, null=True, verbose_name='Business Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Not Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
