# Generated by Django 4.2.2 on 2023-11-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_category_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.AddField(
            model_name='user',
            name='business_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Food', 'Food'), ('Banking', 'Banking'), ('Aviation', 'Aviation'), ('E-commerce', 'E-commerce'), ('Vehicles & Automobiles', 'Vehicles & Automobiles'), ('Agriculture', 'Agriculture')], max_length=30, null=True, verbose_name='Business Category'),
        ),
    ]
