# Generated by Django 4.2.2 on 2023-11-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_category_user_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Business Name'),
        ),
    ]
