# Generated by Django 4.2.2 on 2023-11-17 15:49

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_country_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_category',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Food', 'Food'), ('Banking', 'Banking'), ('Aviation', 'Aviation'), ('E-commerce', 'E-commerce'), ('Vehicles & Automobiles', 'Vehicles & Automobiles'), ('Agriculture', 'Agriculture')], max_length=30, null=True, verbose_name='Business Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Maria Rodriguez', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
