# Generated by Django 4.2.2 on 2023-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_seller'),
        ('user', '0010_user_opening_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opening_days',
            field=models.ManyToManyField(blank=True, null=True, to='api.openingday', verbose_name='Opening Days'),
        ),
    ]
